export const enumConstants = {
    AUTHENTICATION_INIT: 'AUTHENTICATION_INIT',
    AUTHENTICATION_INIT_SUCCESS: 'AUTHENTICATION_INIT_SUCCESS',
    AUTHENTICATION_INIT_FAILED: 'AUTHENTICATION_INIT_FAILED',

    TICKET_ADD_INIT: 'TICKET_ADD_INIT',
    TICKET_ADD_INIT_SUCCESS: 'TICKETS_ADD_INIT_SUCCESS',
    TICKET_ADD_INIT_FAILED: 'TICKETS_ADD_INIT_FAILED',

    TRAINS_FOUND_INIT: 'TRAINS_FOUND_INIT',
    TRAINS_FOUND_INIT_SUCCESS: 'TRAINS_FOUND_INIT_SUCCESS',
    TRAINS_FOUND_INIT_FAILED: 'TRAINS_FOUND_INIT_FAILED',

    TICKET_PURCHASE_INIT: 'TICKET_PURCHASE_INIT',
    TICKET_PURCHASE_INIT_SUCCESS: 'TICKET_PURCHASE_INIT_SICCESS',
    TICKET_PURCHASE_INIT_FAILED: 'TICKET_PURCHASE_INIT_FAILED',
}